services:
  spark:
    image: apache/spark:4.1.3-java17
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ./benchmark/spark-comet:/spark-comet
      - ./benchmark/join-shuffle:/join-shuffle
      - ./benchmark/m3.6:/m3.6
      - ./benchmark/m3.8:/m3.8
