[workspace]
changelog_update = true
git_release_enable = true
git_tag_name = "{{ package }}-v{{ version }}"

[[package]]
name = "pipeline"
release = false
publish = false

[[package]]
name = "typestate"
release = false
publish = false

[[package]]
name = "rusty-ready"
release = false
publish = false

[[package]]
name = "contracts"
release = false
publish = false

[[package]]
name = "contracts-derive"
release = false
publish = false
